name: ubunturdp
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'GRDP Authorization Code'
        required: true
        default: '291NDMWauMpBiOjgN2XLTvkBkcn_HkzfVm4zJPcb8seNT7fKe'
  
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Creating User to Login
      run: |
         sudo useradd -m Area69Lab && sudo adduser Area69Lab sudo && echo 'Area69Lab:Area69Lab' | sudo chpasswd
     
      # To Install different Environment replace their commands. by default it Install 'Ubuntu'
      
      # Ubuntu default will take upto 6-7 min
      # sudo apt update && sudo apt install ubuntu-desktop
      
      # For UKUI (Awesome UI) (4-5 min)
      # sudo add-apt-repository ppa:ubuntukylin-members/ukui -y && sudo apt update && sudo apt install ukui-desktop-environment
      
      # For LXDE (4 min)
      # sudo apt update && sudo apt install lxqt sddm -y
      
      # For Mate (5 min)
      # sudo apt update && sudo apt install ubuntu-mate-desktop -y
      
      # For Budgie (8 min)
      # sudo apt update && sudo apt install ubuntu-budgie-desktop -y
      
      # For KDE Plasma (10 min)
      # sudo apt update && sudo apt install tasksel && sudo tasksel install kubuntu-desktop
      
      # For Deepin (3-4 min)
      # sudo apt update && sudo add-apt-repository ppa:ubuntudde-dev/stable -y && sudo apt install ubuntudde-dde
      
      # For XFCE (2-3 min) Lite weight
      # sudo apt update && sudo apt install xfce4 && sudo chmod 777 /home/Area69Lab/
      # sudo bash -c 'echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" > /etc/chrome-remote-desktop-session'

    - name: Installing Desktop Environment (wait for 10 min)
      run: rm -rf ngrok  ngrok-stable-linux-amd64.zip > /dev/null 2>&1
           echo "Download ngrok"
           wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip > /dev/null 2>&1
           unzip ngrok-stable-linux-amd64.zip > /dev/null 2>&1
           unzip ngrok-stable-linux-amd64.zip.1 > /dev/null 2>&1
           ./ngrok authtoken 291NDMWauMpBiOjgN2XLTvkBkcn_HkzfVm4zJPcb8seNT7fK
           nohup ./ngrok tcp 3389 &>/dev/null &
           sudo apt update && apt upgrade -y
           sudo apt install firefox -y
           sudo apt install -y xrdp
           sudo apt install xfce4 -y
           sudo apt-get install -y xfce4-terminal
           sudo sed -i.bak '/fi/a xfce4-session \n' /etc/xrdp/startwm.sh
           sudo service xrdp start
           clear
           echo XRDP Address:
           curl --silent --show-error http://127.0.0.1:4040/api/tunnels | sed -nE 's/.*public_url":"tcp:..([^"]*).*/\1/p'
           echo "===================================="
           echo "More  Free VPS akuh.net"
           echo "===================================="
           sleep 43200
